import Foundation

enum TabSuggestions {
    typealias Suggestion = (text: String, prompt: String)

    static func forTab(_ tab: AppTab, locale: String) -> [Suggestion] {
        let lang = String(locale.prefix(2))
        switch tab {
        case .home: return home[lang] ?? home["en"]!
        case .activity: return activity[lang] ?? activity["en"]!
        case .card: return card[lang] ?? card["en"]!
        case .settings: return settings[lang] ?? settings["en"]!
        }
    }

    // MARK: - Home

    private static let home: [String: [Suggestion]] = [
        "en": [
            ("Check my balance", "What's my total balance?"),
            ("How's my vault doing?", "Show my vault balance and yield earned"),
            ("Recent activity", "Show my recent transactions"),
            ("Fund my wallet", "How do I deposit USDC?"),
            ("Show my deposit address", "Show my wallet address and QR code to receive USDC"),
            ("How much yield today?", "How much yield have I earned today?"),
            ("Allocate my funds", "Help me split my funds between vault and card"),
            ("What's my APY?", "What's the current vault APY?"),
            ("Move to vault", "I want to move funds from my wallet to the vault"),
            ("Top up my card", "Top up my card from the vault"),
            ("Send USDC", "I want to send USDC to someone"),
            ("Projected earnings", "How much will I earn this month at the current APY?"),
            ("Am I saving enough?", "Based on my spending, am I saving enough?"),
            ("Withdraw from vault", "I want to withdraw USDC from my vault"),
            ("What chain am I on?", "What blockchain network does Nola use?"),
            ("Explain USDC", "What is USDC and how does it work?"),
            ("Show my wallet address", "What's my wallet address?"),
            ("Vault vs card split", "How are my funds split between vault and card?"),
        ],
        "ja": [
            ("残高を確認", "What's my total balance?"),
            ("ボルトの状況は？", "Show my vault balance and yield earned"),
            ("最近のアクティビティ", "Show my recent transactions"),
            ("ウォレットに入金", "How do I deposit USDC?"),
            ("入金アドレスを表示", "Show my wallet address and QR code to receive USDC"),
            ("今日の利回りは？", "How much yield have I earned today?"),
            ("資金を配分", "Help me split my funds between vault and card"),
            ("APYはいくら？", "What's the current vault APY?"),
            ("ボルトに移動", "I want to move funds from my wallet to the vault"),
            ("カードをチャージ", "Top up my card from the vault"),
            ("USDCを送金", "I want to send USDC to someone"),
            ("予想収益", "How much will I earn this month at the current APY?"),
            ("十分貯蓄できている？", "Based on my spending, am I saving enough?"),
            ("ボルトから出金", "I want to withdraw USDC from my vault"),
            ("どのチェーンを使用？", "What blockchain network does Nola use?"),
            ("USDCとは？", "What is USDC and how does it work?"),
            ("ウォレットアドレスを表示", "What's my wallet address?"),
            ("ボルトとカードの配分", "How are my funds split between vault and card?"),
        ],
        "ar": [
            ("تحقق من رصيدي", "What's my total balance?"),
            ("كيف حال خزنتي؟", "Show my vault balance and yield earned"),
            ("النشاط الأخير", "Show my recent transactions"),
            ("تمويل محفظتي", "How do I deposit USDC?"),
            ("عرض عنوان الإيداع", "Show my wallet address and QR code to receive USDC"),
            ("كم الأرباح اليوم؟", "How much yield have I earned today?"),
            ("توزيع أموالي", "Help me split my funds between vault and card"),
            ("ما هو عائدي السنوي؟", "What's the current vault APY?"),
            ("نقل إلى الخزنة", "I want to move funds from my wallet to the vault"),
            ("شحن بطاقتي", "Top up my card from the vault"),
            ("إرسال USDC", "I want to send USDC to someone"),
            ("الأرباح المتوقعة", "How much will I earn this month at the current APY?"),
            ("هل أدّخر بما يكفي؟", "Based on my spending, am I saving enough?"),
            ("سحب من الخزنة", "I want to withdraw USDC from my vault"),
            ("أي شبكة أستخدم؟", "What blockchain network does Nola use?"),
            ("ما هو USDC؟", "What is USDC and how does it work?"),
            ("عرض عنوان محفظتي", "What's my wallet address?"),
            ("توزيع الخزنة والبطاقة", "How are my funds split between vault and card?"),
        ],
        "de": [
            ("Kontostand prüfen", "What's my total balance?"),
            ("Wie steht mein Tresor?", "Show my vault balance and yield earned"),
            ("Letzte Aktivität", "Show my recent transactions"),
            ("Wallet aufladen", "How do I deposit USDC?"),
            ("Einzahlungsadresse anzeigen", "Show my wallet address and QR code to receive USDC"),
            ("Heutiger Ertrag?", "How much yield have I earned today?"),
            ("Mittel aufteilen", "Help me split my funds between vault and card"),
            ("Wie hoch ist mein APY?", "What's the current vault APY?"),
            ("In den Tresor verschieben", "I want to move funds from my wallet to the vault"),
            ("Karte aufladen", "Top up my card from the vault"),
            ("USDC senden", "I want to send USDC to someone"),
            ("Voraussichtliche Erträge", "How much will I earn this month at the current APY?"),
            ("Spare ich genug?", "Based on my spending, am I saving enough?"),
            ("Aus dem Tresor abheben", "I want to withdraw USDC from my vault"),
            ("Welche Blockchain nutze ich?", "What blockchain network does Nola use?"),
            ("Was ist USDC?", "What is USDC and how does it work?"),
            ("Wallet-Adresse anzeigen", "What's my wallet address?"),
            ("Tresor- vs. Kartenaufteilung", "How are my funds split between vault and card?"),
        ],
    ]

    // MARK: - Activity

    private static let activity: [String: [Suggestion]] = [
        "en": [
            ("Spending breakdown", "Show my spending breakdown by category"),
            ("Biggest transactions", "What were my largest transactions this month?"),
            ("Search transactions", "Help me find a specific transaction"),
            ("Today's spending", "How much have I spent today?"),
            ("This week's activity", "Show me this week's transactions"),
            ("Any pending transfers?", "Do I have any pending transactions?"),
            ("Card vs wallet spend", "Compare my card spending vs wallet transfers"),
            ("Last deposit", "When was my last deposit and how much?"),
            ("Monthly summary", "Give me a summary of this month's activity"),
            ("Top merchants", "Which merchants have I spent the most at?"),
            ("Recurring charges", "Do I have any recurring card charges?"),
            ("Failed transactions", "Were there any failed transactions recently?"),
            ("Last card purchase", "What was my last card purchase?"),
            ("Explain a transaction", "Help me understand a specific transaction"),
        ],
        "ja": [
            ("支出の内訳", "Show my spending breakdown by category"),
            ("最大の取引", "What were my largest transactions this month?"),
            ("取引を検索", "Help me find a specific transaction"),
            ("今日の支出", "How much have I spent today?"),
            ("今週のアクティビティ", "Show me this week's transactions"),
            ("保留中の送金は？", "Do I have any pending transactions?"),
            ("カードとウォレットの支出比較", "Compare my card spending vs wallet transfers"),
            ("最後の入金", "When was my last deposit and how much?"),
            ("月間サマリー", "Give me a summary of this month's activity"),
            ("上位の加盟店", "Which merchants have I spent the most at?"),
            ("定期的な請求", "Do I have any recurring card charges?"),
            ("失敗した取引", "Were there any failed transactions recently?"),
            ("最後のカード決済", "What was my last card purchase?"),
            ("取引を説明", "Help me understand a specific transaction"),
        ],
        "ar": [
            ("تفصيل الإنفاق", "Show my spending breakdown by category"),
            ("أكبر المعاملات", "What were my largest transactions this month?"),
            ("البحث في المعاملات", "Help me find a specific transaction"),
            ("إنفاق اليوم", "How much have I spent today?"),
            ("نشاط هذا الأسبوع", "Show me this week's transactions"),
            ("أي تحويلات معلقة؟", "Do I have any pending transactions?"),
            ("إنفاق البطاقة مقابل المحفظة", "Compare my card spending vs wallet transfers"),
            ("آخر إيداع", "When was my last deposit and how much?"),
            ("ملخص الشهر", "Give me a summary of this month's activity"),
            ("أكثر المتاجر", "Which merchants have I spent the most at?"),
            ("رسوم متكررة", "Do I have any recurring card charges?"),
            ("معاملات فاشلة", "Were there any failed transactions recently?"),
            ("آخر عملية شراء بالبطاقة", "What was my last card purchase?"),
            ("شرح معاملة", "Help me understand a specific transaction"),
        ],
        "de": [
            ("Ausgabenübersicht", "Show my spending breakdown by category"),
            ("Größte Transaktionen", "What were my largest transactions this month?"),
            ("Transaktionen suchen", "Help me find a specific transaction"),
            ("Heutige Ausgaben", "How much have I spent today?"),
            ("Aktivität dieser Woche", "Show me this week's transactions"),
            ("Ausstehende Überweisungen?", "Do I have any pending transactions?"),
            ("Karten- vs. Wallet-Ausgaben", "Compare my card spending vs wallet transfers"),
            ("Letzte Einzahlung", "When was my last deposit and how much?"),
            ("Monatliche Zusammenfassung", "Give me a summary of this month's activity"),
            ("Top-Händler", "Which merchants have I spent the most at?"),
            ("Wiederkehrende Abbuchungen", "Do I have any recurring card charges?"),
            ("Fehlgeschlagene Transaktionen", "Were there any failed transactions recently?"),
            ("Letzter Kartenkauf", "What was my last card purchase?"),
            ("Transaktion erklären", "Help me understand a specific transaction"),
        ],
    ]

    // MARK: - Card

    private static let card: [String: [Suggestion]] = [
        "en": [
            ("Card spending", "How much have I spent on my card this month?"),
            ("Issue a new card", "I want to create a new card"),
            ("Card details", "Show my card number and CVV"),
            ("Freeze a card", "I want to freeze one of my cards"),
            ("Card limit", "What's my current card spending limit?"),
            ("Update my limit", "I want to change my card spending limit"),
            ("How many cards?", "How many active cards do I have?"),
            ("Unfreeze a card", "I want to unfreeze one of my cards"),
            ("Cancel a card", "I want to cancel one of my cards"),
            ("Card balance", "What's my current card balance?"),
            ("Refill threshold", "What's my Auto Earn refill threshold?"),
            ("Top up from vault", "Move funds from vault to my card"),
            ("Where can I use it?", "Where can I use my Nola card?"),
        ],
        "ja": [
            ("カード支出", "How much have I spent on my card this month?"),
            ("新しいカードを発行", "I want to create a new card"),
            ("カード詳細", "Show my card number and CVV"),
            ("カードを凍結", "I want to freeze one of my cards"),
            ("カード限度額", "What's my current card spending limit?"),
            ("限度額を変更", "I want to change my card spending limit"),
            ("カード枚数は？", "How many active cards do I have?"),
            ("カードの凍結解除", "I want to unfreeze one of my cards"),
            ("カードをキャンセル", "I want to cancel one of my cards"),
            ("カード残高", "What's my current card balance?"),
            ("チャージしきい値", "What's my Auto Earn refill threshold?"),
            ("ボルトからチャージ", "Move funds from vault to my card"),
            ("どこで使える？", "Where can I use my Nola card?"),
        ],
        "ar": [
            ("إنفاق البطاقة", "How much have I spent on my card this month?"),
            ("إصدار بطاقة جديدة", "I want to create a new card"),
            ("تفاصيل البطاقة", "Show my card number and CVV"),
            ("تجميد بطاقة", "I want to freeze one of my cards"),
            ("حد البطاقة", "What's my current card spending limit?"),
            ("تحديث الحد", "I want to change my card spending limit"),
            ("كم عدد بطاقاتي؟", "How many active cards do I have?"),
            ("إلغاء تجميد بطاقة", "I want to unfreeze one of my cards"),
            ("إلغاء بطاقة", "I want to cancel one of my cards"),
            ("رصيد البطاقة", "What's my current card balance?"),
            ("حد إعادة التعبئة", "What's my Auto Earn refill threshold?"),
            ("شحن من الخزنة", "Move funds from vault to my card"),
            ("أين يمكنني استخدامها؟", "Where can I use my Nola card?"),
        ],
        "de": [
            ("Kartenausgaben", "How much have I spent on my card this month?"),
            ("Neue Karte erstellen", "I want to create a new card"),
            ("Kartendetails", "Show my card number and CVV"),
            ("Karte sperren", "I want to freeze one of my cards"),
            ("Kartenlimit", "What's my current card spending limit?"),
            ("Limit ändern", "I want to change my card spending limit"),
            ("Wie viele Karten?", "How many active cards do I have?"),
            ("Karte entsperren", "I want to unfreeze one of my cards"),
            ("Karte kündigen", "I want to cancel one of my cards"),
            ("Kartenguthaben", "What's my current card balance?"),
            ("Nachfüllschwelle", "What's my Auto Earn refill threshold?"),
            ("Vom Tresor aufladen", "Move funds from vault to my card"),
            ("Wo kann ich sie nutzen?", "Where can I use my Nola card?"),
        ],
    ]

    // MARK: - Settings

    private static let settings: [String: [Suggestion]] = [
        "en": [
            ("Auto Earn help", "Explain how Auto Earn works"),
            ("Create a ticket", "I need help with something"),
            ("Export my wallet", "How do I export my wallet?"),
            ("Change my name", "I want to update my profile name"),
            ("Check my tickets", "Show my support tickets"),
            ("Set a budget", "Help me set a monthly spending budget"),
            ("AI permissions", "What can the AI assistant access?"),
            ("How does Nola work?", "Explain how the Nola app works"),
            ("Change spend limit", "I want to change my spend limit allocation"),
            ("Enable Auto Earn", "Turn on Auto Earn for me"),
            ("Referral code", "What's my referral code?"),
            ("Notification settings", "Help me manage my notification preferences"),
            ("Security tips", "How do I keep my account secure?"),
            ("Contact support", "I need to talk to a human for help"),
        ],
        "ja": [
            ("自動運用ヘルプ", "Explain how Auto Earn works"),
            ("チケットを作成", "I need help with something"),
            ("ウォレットをエクスポート", "How do I export my wallet?"),
            ("名前を変更", "I want to update my profile name"),
            ("チケットを確認", "Show my support tickets"),
            ("予算を設定", "Help me set a monthly spending budget"),
            ("AIの権限", "What can the AI assistant access?"),
            ("Nolaの仕組みは？", "Explain how the Nola app works"),
            ("利用限度額を変更", "I want to change my spend limit allocation"),
            ("自動運用を有効化", "Turn on Auto Earn for me"),
            ("紹介コード", "What's my referral code?"),
            ("通知設定", "Help me manage my notification preferences"),
            ("セキュリティのヒント", "How do I keep my account secure?"),
            ("サポートに連絡", "I need to talk to a human for help"),
        ],
        "ar": [
            ("مساعدة الكسب التلقائي", "Explain how Auto Earn works"),
            ("إنشاء تذكرة", "I need help with something"),
            ("تصدير محفظتي", "How do I export my wallet?"),
            ("تغيير اسمي", "I want to update my profile name"),
            ("التحقق من تذاكري", "Show my support tickets"),
            ("تحديد ميزانية", "Help me set a monthly spending budget"),
            ("أذونات AI", "What can the AI assistant access?"),
            ("كيف يعمل Nola؟", "Explain how the Nola app works"),
            ("تغيير حد الإنفاق", "I want to change my spend limit allocation"),
            ("تفعيل الكسب التلقائي", "Turn on Auto Earn for me"),
            ("رمز الإحالة", "What's my referral code?"),
            ("إعدادات الإشعارات", "Help me manage my notification preferences"),
            ("نصائح أمنية", "How do I keep my account secure?"),
            ("التواصل مع الدعم", "I need to talk to a human for help"),
        ],
        "de": [
            ("Auto-Verdienen-Hilfe", "Explain how Auto Earn works"),
            ("Ticket erstellen", "I need help with something"),
            ("Wallet exportieren", "How do I export my wallet?"),
            ("Namen ändern", "I want to update my profile name"),
            ("Tickets prüfen", "Show my support tickets"),
            ("Budget festlegen", "Help me set a monthly spending budget"),
            ("KI-Berechtigungen", "What can the AI assistant access?"),
            ("Wie funktioniert Nola?", "Explain how the Nola app works"),
            ("Ausgabenlimit ändern", "I want to change my spend limit allocation"),
            ("Auto-Verdienen aktivieren", "Turn on Auto Earn for me"),
            ("Empfehlungscode", "What's my referral code?"),
            ("Benachrichtigungseinstellungen", "Help me manage my notification preferences"),
            ("Sicherheitstipps", "How do I keep my account secure?"),
            ("Support kontaktieren", "I need to talk to a human for help"),
        ],
    ]
}
